import { Inter } from 'next/font/google';
import './globals.css';

import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children, routeParam }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div>
					<div className="mb-[100vh]">
						<Link href="/">home</Link>
						<Link href="/page2">page2</Link>
					</div>

					{children}
					{/* ^ this will be ->  <div className="h-[800px] bg-pink-400"></div> */}
					{/* <div className="mt-[100vh]"></div> */}
				</div>
			</body>
		</html>
	);
}
