import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className="h-[360px] bg-slate-500"></div>
				{children}
				{/* ^ this will be ->  <div className="h-[800px] mt-[400px] mb-[400px] bg-pink-400"></div> */}
				<div>
					<Link href="/">home</Link>
					<Link href="/page2">page2</Link>
				</div>
			</body>
		</html>
	);
}
